import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
test('offline safety caches reads but blocks writes',async()=>{const api=await read('lib/api-client.ts'),db=await read('lib/offline-db.ts');assert.match(api,/SAFE_GET_CACHE/);assert.match(api,/offline_write_blocked/);assert.match(db,/indexedDB\.open/);assert.ok(!api.includes('/api/customers"]'))});
test('mobile shell exposes persistent operational navigation',async()=>{const shell=await read('components/app-shell.tsx');assert.match(shell,/mobilePrimary/);assert.match(shell,/mobileMore/);assert.match(shell,/MoreHorizontal/);for(const p of ['/pos','/queue','/stock','/orders','/settings'])assert.ok(shell.includes(p))});
test('full backup restore requires preview revision and explicit replacement',async()=>{const page=await read('app/backup/page.tsx');assert.match(page,/\/api\/admin\/backup\/preview/);assert.match(page,/\/api\/admin\/backup\/restore/);assert.match(page,/expectedRevision/);assert.match(page,/confirm:true/);assert.match(page,/replace/)});
test('expired sessions immediately return UI to sign in',async()=>{const gate=await read('components/auth-gate.tsx'),client=await read('lib/api-client.ts');assert.match(gate,/field:auth-expired/);assert.match(client,/res\.status===401/)});
test('POS availability disables unavailable products and variants before payment',async()=>{const pos=await read('app/pos/page.tsx'),api=await read('lib/api.mjs');assert.match(api,/buildPosAvailability/);assert.match(api,/availabilityStock/);assert.match(pos,/disabled=\{!x\.available\}/);assert.match(pos,/disabled=\{!canAdd\}/);assert.match(pos,/additionalServingsAvailable/);assert.match(pos,/เพิ่มไม่ได้ · ตะกร้าใช้สต๊อกที่เหลือแล้ว/);assert.match(pos,/หมดชั่วคราว/);assert.match(pos,/cartAvailability/);assert.match(pos,/additionalServingsAvailable/)});
test('POS gives an actionable stock setup path when every sellable product is unavailable',async()=>{const pos=await read('app/pos/page.tsx');assert.match(pos,/ตั้งยอดเริ่มต้น Stock/);assert.match(pos,/router\.push\("\/stock"\)/);assert.match(pos,/เมนูทั้งหมดถูกพักขายชั่วคราว/)});
test('POS and product management render menu photos and offer a real file upload control',async()=>{const pos=await read('app/pos/page.tsx'),products=await read('app/products/page.tsx');assert.match(pos,/x\.image/);assert.match(products,/type="file"/);assert.match(products,/accept="image\/jpeg,image\/png,image\/webp"/);assert.match(products,/compressMenuImage/);assert.match(products,/\/image/)});

test('POS removes stale unavailable persisted cart items before checkout',async()=>{const pos=await read('app/pos/page.tsx');assert.match(pos,/!currentVariant\.available/);assert.match(pos,/ออกจากตะกร้าอัตโนมัติ/);assert.match(pos,/blockedKeys=new Set/);assert.match(pos,/กด CHECKOUT อีกครั้ง/)});

test('login does not publicly prefill the admin username',async()=>{const gate=await read('components/auth-gate.tsx');assert.match(gate,/setUsername\]=useState\(""/);assert.doesNotMatch(gate,/useState\("admin"\)/)});

test('browser security headers block clickjacking without disabling same-origin camera work',async()=>{const raw=await read('vercel.json'),config=JSON.parse(raw),headers=config.headers?.[0]?.headers||[],byKey=Object.fromEntries(headers.map(x=>[x.key,x.value]));assert.equal(byKey['X-Frame-Options'],'DENY');assert.match(byKey['Content-Security-Policy']||'',/frame-ancestors 'none'/);assert.match(byKey['Content-Security-Policy']||'',/object-src 'none'/);assert.equal(byKey['Permissions-Policy'],'geolocation=(), microphone=()')});
test('mobile controls use direct touch manipulation and respect reduced motion',async()=>{const css=await read('app/globals.css');assert.match(css,/touch-action:manipulation/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/-webkit-text-size-adjust:100%/)});
