import test from "node:test";
import assert from "node:assert/strict";
import {readFile,stat} from "node:fs/promises";
const read=p=>readFile(new URL("../"+p,import.meta.url),"utf8");

test("PWA manifest is installable and uses FIELD non-black splash colors",async()=>{const manifest=await read("app/manifest.ts");assert.match(manifest,/name:"FIELD POS"/);assert.match(manifest,/start_url:"\\/pos"/);assert.match(manifest,/display:"standalone"/);assert.match(manifest,/orientation:"portrait-primary"/);assert.match(manifest,/192x192/);assert.match(manifest,/512x512/);assert.match(manifest,/#F7F1E3/);assert.match(manifest,/#1F4D3A/);await stat(new URL("../public/field-icon-192.png",import.meta.url));await stat(new URL("../public/field-icon-512.png",import.meta.url));await stat(new URL("../public/field-icon-180.png",import.meta.url))});
test("service worker never caches API and only updates after explicit safe request",async()=>{const sw=await read("public/sw.js");assert.match(sw,/request\.method!==["']GET["']/);assert.match(sw,/url\.pathname\.startsWith\(["']\\/api\\/["']\)/);assert.match(sw,/SKIP_WAITING/);const install=sw.slice(sw.indexOf('self.addEventListener("install"'),sw.indexOf('self.addEventListener("activate"'));assert.doesNotMatch(install,/skipWaiting\(/)});
test("PWA runtime blocks reload while transaction recovery state is active",async()=>{const runtime=await read("components/pwa-runtime.tsx");assert.match(runtime,/field-pos-pending-promptpay-v1/);assert.match(runtime,/field-pos-pending-cash-v1/);assert.match(runtime,/field-pos-split-group-v1/);assert.match(runtime,/field:transaction-busy/);assert.match(runtime,/field:sync/);assert.match(runtime,/pendingReloadRef/);assert.match(runtime,/beforeinstallprompt/)});
test("layout exposes standalone metadata apple icon and safe viewport",async()=>{const layout=await read("app/layout.tsx");assert.match(layout,/manifest:"\\/manifest\.webmanifest"/);assert.match(layout,/field-icon-180\.png/);assert.match(layout,/viewportFit:"cover"/);assert.match(layout,/mobile-web-app-capable/)});
test("PWA readiness shows local cache outbox version and server readiness",async()=>{const ui=await read("components/pwa-readiness.tsx"),settings=await read("app/settings/page.tsx");assert.match(ui,/Service Worker/);assert.match(ui,/IndexedDB/);assert.match(ui,/Offline Outbox/);assert.match(ui,/Server Revision/);assert.match(ui,/PromptPay/);assert.match(settings,/PwaReadiness/)});
test("network status supports syncing and recoverable sync errors",async()=>{const net=await read("components/network-status.tsx");assert.match(net,/syncing/);assert.match(net,/sync_error/);assert.match(net,/field:sync/)});
test("POS menu images are lazy and PWA shell prioritizes core operator routes",async()=>{const pos=await read("app/pos/page.tsx"),shell=await read("components/app-shell.tsx");assert.match(pos,/loading="lazy"/);assert.match(pos,/decoding="async"/);assert.match(shell,/mobileOrder=\["\\/pos","\\/queue","\\/orders","\\/stock"/)});
test("service worker and manifest bypass deployment cache staleness",async()=>{const config=JSON.parse(await read("vercel.json")),sw=(config.headers||[]).find(x=>x.source==="/sw.js");assert.ok(sw);const byKey=Object.fromEntries(sw.headers.map(x=>[x.key,x.value]));assert.match(byKey["Cache-Control"]||"",/no-cache/);assert.equal(byKey["Service-Worker-Allowed"],"/")});
