import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
test('admin readiness is read-only and exposes operational readiness without provider secrets',async()=>{const api=await read('lib/api.mjs');const start=api.indexOf("if(path==='/api/admin/readiness'"),end=api.indexOf("if(path==='/api/admin/business-settings'",start);assert.ok(start>0&&end>start);const seg=api.slice(start,end);assert.match(seg,/promptPayConfig\(\)/);for(const field of ['readyForCashSales','readyForPromptPay','readyForFullOperations','openOrders','pendingPayments','splitCollecting','splitRequiresResolution','missingCost','pendingCost','lowStock','availableMenus','availableVariants','no_available_menu'])assert.match(seg,new RegExp(field));assert.doesNotMatch(seg,/OMISE_SECRET_KEY|secret\(/);assert.doesNotMatch(seg,/UPDATE |INSERT |DELETE /)});
test('settings surfaces readiness without exposing secrets',async()=>{const ui=await read('app/settings/page.tsx');assert.match(ui,/SYSTEM READINESS/);assert.match(ui,/READY FOR CASH SALES/);assert.match(ui,/\/api\/admin\/readiness/);assert.match(ui,/PromptPay/);assert.doesNotMatch(ui,/OMISE_SECRET_KEY/)});


test('readiness cash flag is gated by actual stock availability',async()=>{const api=await read('lib/api.mjs');const start=api.indexOf("if(path==='/api/admin/readiness'"),end=api.indexOf("if(path==='/api/admin/business-settings'",start),seg=api.slice(start,end);assert.match(seg,/buildPosAvailability/);assert.match(seg,/availableVariants>0/);assert.match(seg,/no_available_menu/)});


test('terminal orders do not create false readiness warnings',async()=>{const api=await read('lib/api.mjs');const start=api.indexOf("if(path==='/api/admin/readiness'"),end=api.indexOf("if(path==='/api/admin/business-settings'",start),seg=api.slice(start,end);assert.match(seg,/\['returned','void','refunded','cancelled'\]/)});
