"use client";
import {useEffect,useMemo,useState} from "react"; import {Search,ShieldCheck} from "lucide-react"; import AuthGate from "@/components/auth-gate"; import {api,type Session} from "@/lib/api-client";
type Event={id:number;actorId:string|null;actor:string;action:string;details:Record<string,any>;createdAt:number};
const labels:Record<string,string>={pos_checkout:"ขาย",sale_void:"Void",sale_refund:"Refund",close_day:"ปิดวัน",stock_ingredient_update:"แก้สต็อก",recipe_publish:"เผยแพร่สูตร",product_create:"สร้างสินค้า",product_update:"แก้สินค้า",product_archive:"ปิดสินค้า",user_create:"สร้างผู้ใช้",user_update:"แก้ผู้ใช้",expense_create:"เพิ่มค่าใช้จ่าย",expense_delete:"ลบค่าใช้จ่าย",customer_create:"เพิ่มลูกค้า",customer_update:"แก้ลูกค้า",state_import:"กู้คืนข้อมูล"};
export default function Audit(){return <AuthGate>{s=><View session={s}/>}</AuthGate>}
function View({session}:{session:Session}){const [rows,setRows]=useState<Event[]>([]),[q,setQ]=useState(""),[busy,setBusy]=useState(true),[err,setErr]=useState("");const load=()=>{setBusy(true);setErr("");return api<{events:Event[]}>("/api/admin/audit").then(x=>setRows(x.events||[])).catch((e:any)=>setErr(e.message)).finally(()=>setBusy(false))};useEffect(()=>{if(session.user.role==="admin")load()},[]);
if(session.user.role!=="admin")return <div className="grid h-full place-items-center text-neutral-500">Admin permission required</div>;
const list=useMemo(()=>{const s=q.trim().toLowerCase();if(!s)return rows;return rows.filter(x=>(x.action+" "+x.actor+" "+JSON.stringify(x.details)).toLowerCase().includes(s))},[rows,q]);
return <section className="flex h-full min-h-0 flex-col p-5 md:p-7"><header className="flex items-end justify-between gap-4"><div><p className="gold m-0 text-[10px] font-bold tracking-[.3em]">SECURITY & TRACEABILITY</p><h1 className="mt-1 text-2xl font-semibold">AUDIT TRAIL</h1></div><button onClick={load} disabled={busy} className="rounded-full border border-white/10 px-4 py-2 text-xs disabled:opacity-40">REFRESH</button></header><div className="glass mt-5 flex items-center gap-3 rounded-full px-4 py-3"><Search size={17} className="text-neutral-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา action / ผู้ใช้ / รายละเอียด" className="w-full bg-transparent outline-none"/></div>{err&&<div className="mt-4 rounded-2xl border border-red-400/20 p-3 text-sm text-red-300">{err}</div>}<div className="soft-scroll mt-4 min-h-0 flex-1 overflow-auto"><div className="grid gap-2">{list.map(x=><article key={x.id} className="glass card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck size={15} className="gold"/><b>{labels[x.action]||x.action}</b></div><div className="mt-1 text-xs text-neutral-500">{x.actor} · {new Date(x.createdAt).toLocaleString("th-TH",{timeZone:"Asia/Bangkok"})}</div></div><code className="rounded-full bg-white/5 px-3 py-1 text-[10px] text-neutral-500">#{x.id}</code></div><pre className="mt-3 overflow-x-auto whitespace-pre-wrap break-words rounded-[18px] bg-black/25 p-3 text-[11px] leading-5 text-neutral-400">{JSON.stringify(x.details,null,2)}</pre></article>)}{!busy&&!list.length&&<div className="py-16 text-center text-sm text-neutral-600">ไม่พบประวัติ</div>}</div></div></section>}
