"use client";
import {useEffect,useMemo,useState} from "react"; import Link from "next/link"; import {usePathname} from "next/navigation"; import {BarChart3,ClipboardList,ListOrdered,Package2,Settings,ShoppingBag,Sparkles,Boxes,LayoutDashboard,ReceiptText,Users,BookOpenCheck,CalendarCheck2,DatabaseBackup,UserCog,ScrollText,Calculator} from "lucide-react"; import {useAppStore} from "@/stores/app-store"; import {dict} from "@/lib/i18n"; import NetworkStatus from "@/components/network-status"; import {api,type Session} from "@/lib/api-client";
const items=[["/dashboard","dashboard",LayoutDashboard,"report"],["/pos","pos",ShoppingBag,"order"],["/queue","queue",ListOrdered,"queue"],["/products","products",Package2,"admin"],["/stock","stock",Boxes,"stock"],["/costs","costs",Calculator,"admin"],["/expenses","expenses",ReceiptText,"report"],["/customers","customers",Users,"admin"],["/recipes","recipes",BookOpenCheck,"admin"],["/close","close",CalendarCheck2,"report"],["/orders","orders",ClipboardList,"order"],["/reports","reports",BarChart3,"report"],["/backup","backup",DatabaseBackup,"admin"],["/users","users",UserCog,"admin"],["/audit","audit",ScrollText,"admin"],["/settings","settings",Settings,"any"]] as const;
export default function AppShell({children}:{children:React.ReactNode}){const path=usePathname(),lang=useAppStore(s=>s.language),t=dict[lang],[session,setSession]=useState<Session|null>(null);useEffect(()=>{const logged=(e:Event)=>setSession((e as CustomEvent).detail||null),expired=()=>setSession(null);api<Session>("/api/auth/session").then(setSession).catch(()=>{});window.addEventListener("field:session",logged);window.addEventListener("field:auth-expired",expired);return()=>{window.removeEventListener("field:session",logged);window.removeEventListener("field:auth-expired",expired)}},[]);
const allowed=useMemo(()=>items.filter(([, , ,access])=>session&&(access==="any"||session.user.role==="admin"||session.user.permissions?.[access]===true)),[session]);const mobileItems=allowed.filter(([href])=>["/dashboard","/pos","/queue","/stock","/orders","/backup","/settings"].includes(href));
return <div className="h-dvh w-full bg-[#090909] p-2 pb-[78px] md:p-4 md:pb-4"><NetworkStatus/><div className="flex h-full gap-3 md:gap-4">
<aside className="glass card hidden w-[92px] shrink-0 flex-col items-center py-5 md:flex xl:w-[220px]"><div className="mb-6 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full border border-[#d4af37]/60"><Sparkles size={19} className="gold"/></div><div className="hidden xl:block"><b className="tracking-[.3em]">FIELD</b><small className="block text-[10px] text-neutral-500">CAFE POS</small></div></div><nav className="soft-scroll w-full space-y-1 overflow-y-auto px-3">{allowed.map(([href,key,Icon])=><Link key={href} href={href} className={"flex items-center gap-3 rounded-full px-4 py-3 text-sm transition "+(path===href?"bg-[#d4af37] text-black":"text-neutral-400 hover:bg-white/5 hover:text-white")}><Icon size={18}/><span className="hidden xl:block">{t[key]}</span></Link>)}</nav></aside>
<main className="min-w-0 flex-1 overflow-hidden rounded-[30px] border border-white/5 bg-[#0e0e0e] md:rounded-[36px]">{children}</main></div>
{mobileItems.length>0&&<nav className="glass fixed bottom-2 left-2 right-2 z-50 flex items-center gap-1 overflow-x-auto rounded-[28px] p-2 shadow-2xl md:hidden">{mobileItems.map(([href,key,Icon])=><Link key={href} href={href} className={"flex min-w-[62px] flex-1 flex-col items-center gap-1 rounded-[20px] px-2 py-2 text-[9px] "+(path===href?"bg-[#d4af37] font-bold text-black":"text-neutral-400")}><Icon size={18}/><span>{t[key]}</span></Link>)}</nav>}</div>}
