"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {RefreshCw} from "lucide-react";
import {clientStorageStatus} from "@/lib/offline-db";
import {captureClientTelemetry} from "@/lib/client-telemetry";
import {useCartStore} from "@/stores/cart-store";
import {FIELD_APP_VERSION,FIELD_SW_URL,PWA_INSTALL_REQUEST_EVENT,PWA_PERSIST_STORAGE_REQUEST_EVENT,PWA_REFRESH_EVENT,PWA_STATUS_EVENT,PWA_UPDATE_REQUEST_EVENT,type PwaSnapshot} from "@/lib/pwa-meta"; import {hasRecovery} from "@/lib/recovery-storage";
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed";platform?:string}>};
const installedMode=()=>typeof window!=="undefined"&&(window.matchMedia("(display-mode: standalone)").matches||(navigator as any).standalone===true);
const capture=captureClientTelemetry;
export default function PwaRuntime(){
  const cartCount=useCartStore(s=>s.items.reduce((sum,item)=>sum+item.qty,0)),cartCountRef=useRef(cartCount),registrationRef=useRef<ServiceWorkerRegistration|null>(null),installPromptRef=useRef<InstallPromptEvent|null>(null),updateAvailableRef=useRef(false),updateInitiatedRef=useRef(false),pendingReloadRef=useRef(false),transactionBusyRef=useRef(false),syncingRef=useRef(false);
  const [updateAvailable,setUpdateAvailable]=useState(false),[transactionBusy,setTransactionBusy]=useState(false),[syncing,setSyncing]=useState(false);
  useEffect(()=>{cartCountRef.current=cartCount},[cartCount]);
  useEffect(()=>{const viewport=window.visualViewport;const syncViewport=()=>document.documentElement.style.setProperty("--field-visual-viewport-height",Math.round(viewport?.height||window.innerHeight)+"px");syncViewport();viewport?.addEventListener("resize",syncViewport);viewport?.addEventListener("scroll",syncViewport);window.addEventListener("resize",syncViewport);return()=>{viewport?.removeEventListener("resize",syncViewport);viewport?.removeEventListener("scroll",syncViewport);window.removeEventListener("resize",syncViewport)}},[]);
  const unsafeReason=useCallback(()=>{if(cartCountRef.current>0)return "มีสินค้าอยู่ในตะกร้า";try{if(localStorage.getItem("field-pos-pending-promptpay-v1"))return "มี PromptPay ที่ยังต้องตรวจสอบ";if(localStorage.getItem("field-pos-pending-cash-v1"))return "มี Cash Checkout ที่สถานะยังไม่แน่นอน";if(hasRecovery("field-pos-split-group-v1"))return "มี Split Payment ที่ยังไม่จบ";if(hasRecovery("field-pos-edit-cash-v1"))return "กำลังแก้ไขออเดอร์เงินสด"}catch{}if(transactionBusyRef.current)return "มี Queue action กำลังบันทึก";if(syncingRef.current)return "กำลัง Sync Offline sales";return ""},[]);
  const publish=useCallback(async()=>{if(typeof window==="undefined")return null;const storage=await clientStorageStatus().catch(()=>({indexedDbReady:false,cacheReady:false,outboxPending:0,outboxNeedsReview:0,schemaVersion:0}));const persistenceSupported=!!navigator.storage&&typeof navigator.storage.persisted==="function",storagePersisted=persistenceSupported?await navigator.storage.persisted().catch(()=>null):null,estimate=typeof navigator.storage?.estimate==="function"?await navigator.storage.estimate().catch(()=>null):null;const supported="serviceWorker" in navigator;const registration=supported?(registrationRef.current||await navigator.serviceWorker.getRegistration().catch(()=>undefined)):undefined;if(registration)registrationRef.current=registration;const installed=installedMode();const snapshot:PwaSnapshot={appVersion:FIELD_APP_VERSION,installed,installable:installed||!!installPromptRef.current,serviceWorkerSupported:supported,serviceWorkerActive:!!registration?.active,updateAvailable:updateAvailableRef.current,indexedDbReady:storage.indexedDbReady,cacheReady:storage.cacheReady,outboxPending:storage.outboxPending,outboxNeedsReview:storage.outboxNeedsReview,storagePersistenceSupported:persistenceSupported,storagePersisted,storageUsage:Number.isFinite(Number(estimate?.usage))?Number(estimate?.usage):null,storageQuota:Number.isFinite(Number(estimate?.quota))?Number(estimate?.quota):null,online:navigator.onLine,displayMode:installed?"standalone":"browser",lastChecked:Date.now()};window.dispatchEvent(new CustomEvent(PWA_STATUS_EVENT,{detail:snapshot}));return snapshot},[]);
  const requestInstall=useCallback(async()=>{const prompt=installPromptRef.current;if(!prompt)return publish();capture("install_prompt");await prompt.prompt();const choice=await prompt.userChoice.catch(()=>null);if(choice?.outcome==="accepted")capture("installed");installPromptRef.current=null;return publish()},[publish]);
  const requestPersistence=useCallback(async()=>{if(!navigator.storage||typeof navigator.storage.persist!=="function")return publish();const granted=await navigator.storage.persist().catch(()=>false);capture("storage_persistence_request",{granted});return publish()},[publish]);
  const requestUpdate=useCallback(async()=>{if(unsafeReason())return publish();const registration=registrationRef.current||await navigator.serviceWorker?.getRegistration().catch(()=>undefined);if(!registration?.waiting)return publish();updateInitiatedRef.current=true;registration.waiting.postMessage({type:"SKIP_WAITING"});return publish()},[publish,unsafeReason]);
  useEffect(()=>{if(typeof window==="undefined")return;capture("app_launch",{displayMode:installedMode()?"standalone":"browser"});clientStorageStatus().then(x=>capture(x.cacheReady?"cache_launch":"network_launch")).catch(()=>capture("network_launch"));
    const beforeInstall=(event:Event)=>{event.preventDefault();installPromptRef.current=event as InstallPromptEvent;publish()},installed=()=>{installPromptRef.current=null;capture("installed");publish()},online=()=>publish(),offline=()=>{capture("offline_entered");publish()},refresh=()=>{publish()},installRequest=()=>{requestInstall()},persistenceRequest=()=>{requestPersistence()},updateRequest=()=>{requestUpdate()};
    const runtimeError=(event:ErrorEvent)=>capture("runtime_error",{kind:"error",route:window.location.pathname,error_name:String((event.error as any)?.name||"Error").slice(0,80)});
    const unhandledRejection=(event:PromiseRejectionEvent)=>capture("runtime_error",{kind:"unhandledrejection",route:window.location.pathname,error_name:String((event.reason as any)?.name||typeof event.reason||"unknown").slice(0,80)});
    const syncEvent=(event:Event)=>{const status=String((event as CustomEvent).detail?.status||""),active=status==="syncing";syncingRef.current=active;setSyncing(active);if(status==="online")capture("offline_sync_success");if(status==="sync_error")capture("offline_sync_failed");publish()};
    const busyEvent=(event:Event)=>{const active=!!(event as CustomEvent).detail?.busy;transactionBusyRef.current=active;setTransactionBusy(active);publish()};
    const controllerChanged=()=>{if(!updateInitiatedRef.current)return;capture("service_worker_update");if(unsafeReason())pendingReloadRef.current=true;else window.location.reload()};
    window.addEventListener("beforeinstallprompt",beforeInstall);window.addEventListener("appinstalled",installed);window.addEventListener("online",online);window.addEventListener("offline",offline);window.addEventListener("error",runtimeError);window.addEventListener("unhandledrejection",unhandledRejection);window.addEventListener(PWA_REFRESH_EVENT,refresh);window.addEventListener(PWA_INSTALL_REQUEST_EVENT,installRequest);window.addEventListener(PWA_PERSIST_STORAGE_REQUEST_EVENT,persistenceRequest);window.addEventListener(PWA_UPDATE_REQUEST_EVENT,updateRequest);window.addEventListener("field:sync",syncEvent);window.addEventListener("field:transaction-busy",busyEvent);navigator.serviceWorker?.addEventListener("controllerchange",controllerChanged);
    let disposed=false;if("serviceWorker" in navigator&&process.env.NODE_ENV==="production"){navigator.serviceWorker.register(FIELD_SW_URL,{scope:"/",updateViaCache:"none"}).then(registration=>{if(disposed)return;registrationRef.current=registration;const markUpdate=()=>{updateAvailableRef.current=true;setUpdateAvailable(true);capture("service_worker_update",{state:"available"});publish()};if(registration.waiting&&navigator.serviceWorker.controller)markUpdate();registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)markUpdate()})});registration.update().catch(()=>{});publish()}).catch(()=>publish())}else publish();
    return()=>{disposed=true;window.removeEventListener("beforeinstallprompt",beforeInstall);window.removeEventListener("appinstalled",installed);window.removeEventListener("online",online);window.removeEventListener("offline",offline);window.removeEventListener("error",runtimeError);window.removeEventListener("unhandledrejection",unhandledRejection);window.removeEventListener(PWA_REFRESH_EVENT,refresh);window.removeEventListener(PWA_INSTALL_REQUEST_EVENT,installRequest);window.removeEventListener(PWA_PERSIST_STORAGE_REQUEST_EVENT,persistenceRequest);window.removeEventListener(PWA_UPDATE_REQUEST_EVENT,updateRequest);window.removeEventListener("field:sync",syncEvent);window.removeEventListener("field:transaction-busy",busyEvent);navigator.serviceWorker?.removeEventListener("controllerchange",controllerChanged)}
  },[publish,requestInstall,requestPersistence,requestUpdate,unsafeReason]);
  useEffect(()=>{if(pendingReloadRef.current&&!unsafeReason())window.location.reload()},[cartCount,transactionBusy,syncing,unsafeReason]);
  if(!updateAvailable)return null;const reason=unsafeReason();return <div className="fixed left-1/2 top-[max(.6rem,env(safe-area-inset-top))] z-[100] w-[min(92vw,460px)] -translate-x-1/2 rounded-2xl border border-amber-300 bg-amber-50/95 px-4 py-3 text-sm text-amber-950 shadow-xl backdrop-blur"><div className="flex items-center justify-between gap-3"><div><b>มี FIELD POS เวอร์ชันใหม่</b><p className="mt-0.5 text-xs text-amber-800">{reason?"รอให้ปลอดภัยก่อนอัปเดต · "+reason:"พร้อมอัปเดตหลังจบออเดอร์"}</p></div><button disabled={!!reason} onClick={()=>requestUpdate()} className="flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-[#1F4D3A] px-3 font-bold text-white disabled:opacity-45"><RefreshCw size={15}/>อัปเดต</button></div></div>
}
