"use client";
import AuthGate from "@/components/auth-gate";
import {useEffect,useMemo,useState} from "react";
import {api,type Session} from "@/lib/api-client";
import {ImagePlus,Pencil,Plus,Search,Trash2,X} from "lucide-react";

type P={id:string;name:string;category:string;price:number;enabled:boolean;image?:string;archived:boolean;archivedReason?:string;archivedAt?:number|null;variants:{label:string}[]};

async function compressMenuImage(file:File){
  if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("รองรับเฉพาะ JPG, PNG หรือ WebP");
  const bitmap=await createImageBitmap(file);let scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height));
  for(let attempt=0;attempt<6;attempt++){
    const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
    canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);
    const dataUrl=canvas.toDataURL("image/webp",Math.max(.55,.82-attempt*.05));
    if(Math.ceil((dataUrl.length-dataUrl.indexOf(",")-1)*.75)<=180000){bitmap.close();return dataUrl}
    scale*=.78;
  }
  bitmap.close();throw new Error("รูปมีขนาดใหญ่เกินไป กรุณาเลือกรูปอื่น");
}

export default function Products(){return <AuthGate>{s=><ProductsView session={s}/>}</AuthGate>}
function ProductsView({session}:{session:Session}){
  const [products,setProducts]=useState<P[]>([]),[q,setQ]=useState(""),[tab,setTab]=useState<"active"|"archived">("active"),[edit,setEdit]=useState<Partial<P>|null>(null),[del,setDel]=useState<P|null>(null),[archiveReason,setArchiveReason]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[pendingImage,setPendingImage]=useState("");
  const admin=session.user.role==="admin";
  const load=()=>api<{products:P[]}>("/api/admin/products").then(x=>setProducts(x.products));
  useEffect(()=>{if(admin)load().catch(()=>{})},[admin]);
  const rows=useMemo(()=>products.filter(x=>x.archived===(tab==="archived")&&(x.name+" "+x.category).toLowerCase().includes(q.toLowerCase())),[products,q,tab]);
  async function chooseImage(file?:File){if(!file)return;setMsg("");try{setPendingImage(await compressMenuImage(file))}catch(e:any){setMsg(e.message)}}
  async function save(){if(!edit)return;setBusy(true);setMsg("");try{let id=edit.id;if(id)await api("/api/admin/products/"+encodeURIComponent(id),{method:"PATCH",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({name:edit.name,category:edit.category,price:Number(edit.price),enabled:!!edit.enabled})});else{const created=await api<{product:{id:string}}>("/api/admin/products",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({name:edit.name,category:edit.category,price:Number(edit.price)})});id=created.product.id}if(id&&pendingImage)await api("/api/admin/products/"+encodeURIComponent(id)+"/image",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({dataUrl:pendingImage})});setEdit(null);setPendingImage("");await load()}catch(e:any){setMsg(e.message==="price_required_before_enable"?"เมนูที่เปิดขายต้องมีราคามากกว่า 0 บาท":e.message==="recipe_required_before_enable"?"ต้องมีสูตรครบก่อนเปิดขาย":e.message)}finally{setBusy(false)}}
  async function archive(){if(!del||archiveReason.trim().length<3)return;setBusy(true);try{await api("/api/admin/products/"+encodeURIComponent(del.id),{method:"DELETE",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({reason:archiveReason.trim()})});setDel(null);setArchiveReason("");await load()}finally{setBusy(false)}}
  async function restore(product:P){if(!window.confirm("กู้คืน "+product.name+" เป็น Draft? เมนูจะยังไม่เปิดขายจนกว่าจะตรวจสูตรและต้นทุน"))return;setBusy(true);try{await api("/api/admin/products/"+encodeURIComponent(product.id)+"/restore",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:"{}"});await load()}finally{setBusy(false)}}
  async function purge(product:P){if(!window.confirm("ลบ "+product.name+" ถาวร?\nทำได้เฉพาะเมนูทดลองที่ไม่เคยขายและไม่มี Cost History"))return;setBusy(true);setMsg("");try{await api("/api/admin/products/"+encodeURIComponent(product.id)+"/purge",{method:"DELETE",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({confirm:"DELETE"})});setMsg("ลบเมนูทดลองแล้ว");await load()}catch(e:any){setMsg(e.message==="product_has_sales_archive_instead"?"เมนูนี้มีประวัติขายแล้ว จึงลบถาวรไม่ได้ ให้เก็บ/Archive แทน":e.message==="product_has_cost_history_archive_instead"?"เมนูนี้มีประวัติต้นทุนแล้ว จึงลบถาวรไม่ได้":e.message)}finally{setBusy(false)}}
  if(!admin)return <div className="grid h-full place-items-center text-sm text-slate-500">Admin permission required</div>;
  return <section className="flex h-full flex-col p-3 sm:p-5 md:p-7">
    <header className="mb-3 flex flex-wrap items-end justify-between gap-3 sm:mb-5"><div><p className="gold m-0 text-[9px] font-bold tracking-[.26em] sm:text-[10px]">CATALOG</p><h1 className="m-0 mt-1 text-xl font-semibold tracking-wide sm:text-2xl">PRODUCT MANAGEMENT</h1><p className="mt-1 text-xs text-slate-500">Admin เพิ่ม/แก้ราคา/เปิดขาย/เก็บ/ลบเมนูทดลองได้เอง</p></div><button onClick={()=>{setEdit({name:"",category:"MATCHA",price:0,enabled:false,image:""});setPendingImage("")}} className="flex min-h-11 items-center gap-2 rounded-full bg-[#d4af37] px-4 text-sm font-bold text-black"><Plus size={16}/>เพิ่มเมนู</button></header>
    {msg&&<div className="mb-3 flex items-start justify-between rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm"><span>{msg}</span><button onClick={()=>setMsg("")}><X size={16}/></button></div>}<div className="mb-4 grid gap-3 md:grid-cols-[auto_1fr]"><div className="glass flex rounded-full p-1"><button onClick={()=>setTab("active")} className={"rounded-full px-4 py-2 text-xs "+(tab==="active"?"bg-[#d4af37] font-bold text-black":"text-slate-600")}>เมนูใช้งาน</button><button onClick={()=>setTab("archived")} className={"rounded-full px-4 py-2 text-xs "+(tab==="archived"?"bg-[#d4af37] font-bold text-black":"text-slate-600")}>เมนูที่ตัดออก</button></div><div className="glass flex items-center gap-3 rounded-full px-4 py-3"><Search size={18} className="text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาสินค้า" className="w-full bg-transparent outline-none"/></div></div>
    <div className="glass card soft-scroll flex-1 overflow-auto p-2"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-100 text-left text-[10px] uppercase tracking-widest text-slate-500"><tr><th className="p-4">Name</th><th>Category</th><th>Price</th><th>Status / Reason</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t border-slate-200"><td className="p-4"><div className="flex items-center gap-3">{x.image?<img src={x.image} alt="" className="h-12 w-12 rounded-xl object-cover"/>:<div className="grid h-12 w-12 place-items-center rounded-xl bg-slate-100 text-slate-400"><ImagePlus size={18}/></div>}<div className="font-medium">{x.name}<small className="block text-slate-400">{x.variants.map(v=>v.label).join(", ")}</small></div></div></td><td className="text-slate-600">{x.category||"—"}</td><td>฿{x.price.toFixed(0)}</td><td>{x.archived?<div><span className="rounded-full bg-red-400/10 px-3 py-1 text-xs text-red-600">ARCHIVED</span><small className="mt-2 block max-w-sm text-slate-600">{x.archivedReason||"ไม่ระบุเหตุผล"}{x.archivedAt?" · "+new Date(x.archivedAt).toLocaleDateString("th-TH"):""}</small></div>:<span className={"rounded-full px-3 py-1 text-xs "+(x.enabled?"bg-emerald-400/10 text-emerald-700":"bg-amber-400/10 text-amber-700")}>{x.enabled?"ACTIVE":"DRAFT/OFF"}</span>}</td><td>{x.archived?<div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>restore(x)} className="rounded-full border border-amber-400/30 px-3 py-2 text-[10px] font-bold text-amber-700">RESTORE AS DRAFT</button><button disabled={busy} onClick={()=>purge(x)} className="rounded-full border border-red-300 px-3 py-2 text-[10px] font-bold text-red-600">ลบถาวร (ทดลอง)</button></div>:<div className="flex gap-2"><button onClick={()=>{setEdit({...x});setPendingImage("")}} className="grid h-9 w-9 place-items-center rounded-full border border-slate-200"><Pencil size={15}/></button><button onClick={()=>{setDel(x);setArchiveReason("")}} className="grid h-9 w-9 place-items-center rounded-full border border-red-400/20 text-red-600"><Trash2 size={15}/></button></div>}</td></tr>)}</tbody></table>{rows.length===0&&<p className="p-8 text-center text-sm text-slate-500">ไม่พบรายการในหมวดนี้</p>}</div>
    {edit&&<div className="fixed inset-0 z-50 grid place-items-center overflow-auto bg-black/70 p-4"><div className="glass card my-4 w-full max-w-lg p-4 sm:p-6"><div className="flex justify-between"><div><p className="gold text-[10px] tracking-[.25em]">{edit.id?"EDIT PRODUCT":"NEW PRODUCT"}</p><h3 className="mt-1 text-xl">{edit.id?edit.name:"เพิ่มสินค้า"}</h3></div><button onClick={()=>{setEdit(null);setPendingImage("")}}><X/></button></div><div className="mt-5 grid gap-3"><label className="flex cursor-pointer items-center gap-4 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-3"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white">{pendingImage||edit.image?<img src={pendingImage||edit.image} alt="ตัวอย่างรูปเมนู" className="h-full w-full object-cover"/>:<ImagePlus className="text-slate-400"/>}</div><div><b className="text-sm">อัปโหลดรูปเมนู</b><small className="mt-1 block text-slate-500">JPG, PNG หรือ WebP · ระบบย่อรูปก่อนบันทึก</small></div><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseImage(e.target.files?.[0])} className="hidden"/></label><input value={edit.name||""} onChange={e=>setEdit({...edit,name:e.target.value})} placeholder="ชื่อสินค้า" className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none"/><input value={edit.category||""} onChange={e=>setEdit({...edit,category:e.target.value})} placeholder="หมวดหมู่" className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none"/><input type="number" value={Number(edit.price)||0} onChange={e=>setEdit({...edit,price:Number(e.target.value)})} placeholder="ราคา" className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none"/>{edit.id&&<label className="flex items-center justify-between rounded-2xl border border-slate-200 px-4 py-3"><span>เปิดขาย</span><input type="checkbox" checked={!!edit.enabled} onChange={e=>setEdit({...edit,enabled:e.target.checked})} className="h-5 w-5"/></label>}<p className="text-xs text-slate-500">สินค้าใหม่จะเป็น Draft/Off ก่อน เมนูที่เปิดขายต้องมีราคาและสูตรครบ</p>{msg&&<p className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{msg}</p>}<button disabled={busy||!edit.name||Number(edit.price)<0||(!!edit.enabled&&Number(edit.price)<=0)} onClick={save} className="rounded-full bg-[#d4af37] py-3 font-bold text-black disabled:opacity-40">{busy?"SAVING...":"SAVE PRODUCT"}</button></div></div></div>}
    {del&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="glass card w-full max-w-md p-4 sm:p-6"><div className="flex justify-between"><div><p className="gold text-[10px] tracking-[.25em]">ARCHIVE PRODUCT</p><h3 className="mt-1 text-xl">{del.name}</h3></div><button onClick={()=>setDel(null)}><X/></button></div><p className="mt-4 text-sm text-slate-600">เมนูจะถูกตัดออกจาก POS แต่สูตรและประวัติจะยังอยู่</p><textarea value={archiveReason} onChange={e=>setArchiveReason(e.target.value)} placeholder="เหตุผลที่ตัดออก (อย่างน้อย 3 ตัวอักษร)" className="mt-3 min-h-28 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 outline-none"/><button disabled={busy||archiveReason.trim().length<3} onClick={archive} className="mt-4 w-full rounded-full bg-red-600 py-3 font-bold text-white disabled:opacity-40">{busy?"SAVING...":"ยืนยันตัดเมนู"}</button></div></div>}
  </section>;
}
