"use client";
import AuthGate from "@/components/auth-gate"; import {useEffect,useMemo,useState} from "react"; import {api,type Session} from "@/lib/api-client"; import {Pencil,Plus,Search,Trash2,X} from "lucide-react";
type P={id:string;name:string;category:string;price:number;enabled:boolean;image?:string;variants:{label:string}[]};
export default function Products(){return <AuthGate>{s=><ProductsView session={s}/>}</AuthGate>}
function ProductsView({session}:{session:Session}){const [products,setProducts]=useState<P[]>([]),[q,setQ]=useState(""),[edit,setEdit]=useState<Partial<P>|null>(null),[del,setDel]=useState<P|null>(null),[busy,setBusy]=useState(false);const admin=session.user.role==="admin";
const load=()=>api<{products:P[]}>("/api/admin/products").then(x=>setProducts(x.products));useEffect(()=>{if(admin)load().catch(()=>{})},[admin]);
const rows=useMemo(()=>products.filter(x=>(x.name+" "+x.category).toLowerCase().includes(q.toLowerCase())),[products,q]);
async function save(){if(!edit)return;setBusy(true);try{if(edit.id)await api("/api/admin/products/"+encodeURIComponent(edit.id),{method:"PATCH",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({name:edit.name,category:edit.category,price:Number(edit.price),enabled:!!edit.enabled,image:edit.image||""})});else await api("/api/admin/products",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({name:edit.name,category:edit.category,price:Number(edit.price),image:edit.image||""})});setEdit(null);await load()}finally{setBusy(false)}}
async function archive(){if(!del)return;setBusy(true);try{await api("/api/admin/products/"+encodeURIComponent(del.id),{method:"DELETE",headers:{"X-CSRF-Token":session.csrf}});setDel(null);await load()}finally{setBusy(false)}}
if(!admin)return <div className="grid h-full place-items-center text-sm text-neutral-500">Admin permission required</div>;
return <section className="flex h-full flex-col p-5 md:p-7"><header className="mb-5 flex items-end justify-between"><div><p className="gold m-0 text-[10px] font-bold tracking-[.3em]">CATALOG</p><h1 className="m-0 mt-1 text-2xl font-semibold tracking-wide">PRODUCT MANAGEMENT</h1></div><button onClick={()=>setEdit({name:"",category:"MATCHA",price:0,enabled:false,image:""})} className="flex items-center gap-2 rounded-full bg-[#d4af37] px-4 py-2 text-sm font-bold text-black"><Plus size={16}/>ADD PRODUCT</button></header>
<div className="glass mb-4 flex items-center gap-3 rounded-full px-4 py-3"><Search size={18} className="text-neutral-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาสินค้า" className="w-full bg-transparent outline-none"/></div>
<div className="glass card soft-scroll flex-1 overflow-auto p-2"><table className="w-full text-sm"><thead className="sticky top-0 bg-[#151515] text-left text-[10px] uppercase tracking-widest text-neutral-500"><tr><th className="p-4">Name</th><th>Category</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t border-white/5"><td className="p-4 font-medium">{x.name}<small className="block text-neutral-600">{x.variants.map(v=>v.label).join(", ")}</small></td><td className="text-neutral-400">{x.category||"—"}</td><td>฿{x.price.toFixed(0)}</td><td><span className={"rounded-full px-3 py-1 text-xs "+(x.enabled?"bg-emerald-400/10 text-emerald-300":"bg-amber-400/10 text-amber-300")}>{x.enabled?"ACTIVE":"DRAFT/OFF"}</span></td><td><div className="flex gap-2"><button onClick={()=>setEdit({...x})} className="grid h-9 w-9 place-items-center rounded-full border border-white/10"><Pencil size={15}/></button><button onClick={()=>setDel(x)} className="grid h-9 w-9 place-items-center rounded-full border border-red-400/20 text-red-300"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>
{edit&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="glass card w-full max-w-lg p-6"><div className="flex justify-between"><div><p className="gold text-[10px] tracking-[.25em]">{edit.id?"EDIT PRODUCT":"NEW PRODUCT"}</p><h3 className="mt-1 text-xl">{edit.id?edit.name:"เพิ่มสินค้า"}</h3></div><button onClick={()=>setEdit(null)}><X/></button></div><div className="mt-5 grid gap-3"><input value={edit.name||""} onChange={e=>setEdit({...edit,name:e.target.value})} placeholder="ชื่อสินค้า" className="rounded-2xl border border-white/10 bg-black/40 px-4 py-3 outline-none"/><input value={edit.category||""} onChange={e=>setEdit({...edit,category:e.target.value})} placeholder="หมวดหมู่" className="rounded-2xl border border-white/10 bg-black/40 px-4 py-3 outline-none"/><input type="number" value={Number(edit.price)||0} onChange={e=>setEdit({...edit,price:Number(e.target.value)})} placeholder="ราคา" className="rounded-2xl border border-white/10 bg-black/40 px-4 py-3 outline-none"/>{edit.id&&<label className="flex items-center justify-between rounded-2xl border border-white/10 px-4 py-3"><span>เปิดขาย</span><input type="checkbox" checked={!!edit.enabled} onChange={e=>setEdit({...edit,enabled:e.target.checked})} className="h-5 w-5"/></label>}<p className="text-xs text-neutral-500">สินค้าใหม่จะถูกสร้างเป็น Draft/Off ก่อน เพื่อป้องกันขายเมนูที่ยังไม่มีสูตรต้นทุนครบ</p><button disabled={busy||!edit.name||Number(edit.price)<0} onClick={save} className="rounded-full bg-[#d4af37] py-3 font-bold text-black disabled:opacity-40">{busy?"SAVING...":"SAVE PRODUCT"}</button></div></div></div>}
{del&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="glass card w-full max-w-md p-6"><p className="gold text-[10px] tracking-[.25em]">CONFIRM</p><h3 className="mt-1 text-xl">นำ {del.name} ออกจากรายการ?</h3><p className="mt-3 text-sm text-neutral-400">ระบบจะ Archive และปิดขายสินค้า โดยไม่ลบประวัติยอดขายเดิม</p><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>setDel(null)} className="rounded-full border border-white/10 py-3">ยกเลิก</button><button disabled={busy} onClick={archive} className="rounded-full bg-red-500/80 py-3 font-bold text-white">ARCHIVE</button></div></div></div>}</section>}