"use client";
import {useEffect,useMemo,useState} from "react"; import {Layers3,Sparkles} from "lucide-react"; import AuthGate from "@/components/auth-gate"; import {api,type Bootstrap,type Session} from "@/lib/api-client";
type QItem={id:string;name:string;variant:string;qty:number;readyQty?:number;calledQty?:number;prepSelected?:boolean};
type QOrder={id:string;queueNo:string;status:string;time:number;items:QItem[]};
export default function Queue(){return <AuthGate>{s=><QueueView session={s}/>}</AuthGate>}
function QueueView({session}:{session:Session}){const [data,setData]=useState<Bootstrap|null>(null),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");const load=()=>api<Bootstrap>("/api/pos/bootstrap").then(setData);useEffect(()=>{load().catch(()=>{})},[]);
const orders=useMemo(()=>((data?.orders||[]) as QOrder[]).slice().sort((a,b)=>Number(a.time||0)-Number(b.time||0)),[data]);
const assist=useMemo(()=>{let primary:{order:QOrder;item:QItem;index:number;phase:"prepare"|"call"}|null=null;for(const order of orders){for(let i=0;i<(order.items||[]).length;i++){const item=order.items[i],qty=Number(item.qty)||0,ready=Number(item.readyQty)||0,called=Number(item.calledQty)||0;if(called<qty){primary={order,item,index:i,phase:ready<qty?"prepare":"call"};break}}if(primary)break}if(!primary)return {primary:null,batch:[] as {queueNo:string;orderId:string;index:number}[]};const batch=primary.phase==="prepare"?orders.flatMap(order=>(order.items||[]).map((item,index)=>({order,item,index}))).filter(x=>x.order.id!==primary!.order.id&&x.item.id===primary!.item.id&&x.item.variant===primary!.item.variant&&(Number(x.item.readyQty)||0)<(Number(x.item.qty)||0)).map(x=>({queueNo:x.order.queueNo,orderId:x.order.id,index:x.index})):[];return {primary,batch}},[orders]);
async function act(orderId:string,itemIndex:number,action:"start"|"finish"|"select",unit?:number){setBusy(orderId+itemIndex+action);setMsg("");try{await api("/api/pos/queue",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({requestKey:crypto.randomUUID(),orderId,itemIndex,action,unit,selected:true})});await load()}catch(e:any){setMsg(e.message==="queue_state_changed"?"สถานะคิวเปลี่ยนแล้ว ระบบโหลดข้อมูลใหม่ให้":e.message);await load().catch(()=>{})}finally{setBusy("")}}
async function ret(orderId:string){setBusy(orderId+"return");setMsg("");try{await api("/api/pos/queue",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({requestKey:crypto.randomUUID(),orderId,action:"return"})});await load()}catch(e:any){setMsg(e.message==="fifo_violation"?"ต้องส่งมอบคิวก่อนหน้าก่อน":e.message);await load().catch(()=>{})}finally{setBusy("")}}
return <section className="soft-scroll h-full overflow-auto p-5 md:p-7"><div className="flex items-end justify-between gap-4"><div><p className="gold m-0 text-[10px] font-bold tracking-[.3em]">PRODUCTION</p><h1 className="mt-1 text-2xl font-semibold">QUEUE</h1></div><span className="rounded-full border border-slate-200 px-3 py-2 text-xs text-slate-600">{orders.length} ACTIVE</span></div>
{msg&&<div className="mt-4 rounded-2xl border border-amber-400/20 bg-amber-400/[.05] p-3 text-sm text-amber-200">{msg}</div>}
<div className="glass card mt-5 p-5"><div className="flex items-center gap-2"><Sparkles size={17} className="gold"/><b className="text-sm tracking-widest">PRODUCTION ASSIST</b></div>{assist.primary?<div className="mt-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#d4af37] px-3 py-1 text-xs font-bold text-black">ทำก่อน · {assist.primary.order.queueNo}</span><b>{assist.primary.item.name}</b><span className="text-sm text-slate-500">{assist.primary.item.variant}</span></div><p className="mt-2 text-sm text-slate-600">{assist.primary.phase==="prepare"?"เตรียมแก้วถัดไปของคิวแรกก่อน":"รายการของคิวแรกทำแล้ว · ให้เสร็จ/เรียกก่อน"}</p>{assist.batch.length>0&&<div className="mt-3 flex flex-wrap items-center gap-2 text-xs"><span className="flex items-center gap-1 text-slate-600"><Layers3 size={14}/>Batch เตรียมพร้อม:</span>{assist.batch.map(x=><span key={x.orderId+":"+x.index} className="rounded-full border border-slate-200 px-3 py-1 text-slate-700">{x.queueNo}</span>)}<span className="text-amber-700">ส่งมอบยังคง FIFO</span></div>}</div>:<p className="mt-3 text-sm text-emerald-700">ไม่มีรายการค้างผลิต</p>}</div>
<div className="mt-5 grid gap-4 xl:grid-cols-3">{orders.map((o,oi)=><div key={o.id} className={"glass card p-5 "+(oi===0?"border-[#d4af37]/40":"")}><div className="flex items-start justify-between"><div><small className="text-slate-500">QUEUE</small><div className="mt-1 text-3xl font-bold gold">{o.queueNo}</div></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs uppercase text-slate-600">{o.status}</span></div><div className="mt-5 space-y-3">{(o.items||[]).map((x,i)=>{const ready=Number(x.readyQty)||0,called=Number(x.calledQty)||0,qty=Number(x.qty)||0,isPrimary=assist.primary?.order.id===o.id&&assist.primary?.index===i,isBatch=assist.batch.some(b=>b.orderId===o.id&&b.index===i);return <div key={i} className={"rounded-[24px] border p-4 "+(x.prepSelected?"border-[#d4af37]/60 bg-[#d4af37]/[.06]":isPrimary?"border-[#d4af37]/30 bg-slate-50":"border-slate-100 bg-slate-50")}><div className="flex flex-wrap items-center gap-2"><b>{x.name}</b><small className="text-slate-500">{x.variant} ×{qty}</small>{isPrimary&&<span className="rounded-full bg-[#d4af37] px-2 py-1 text-[9px] font-bold text-black">ทำก่อน ★</span>}{isBatch&&<span className="rounded-full border border-sky-400/30 px-2 py-1 text-[9px] text-sky-700">BATCH</span>}{x.prepSelected&&<span className="rounded-full border border-emerald-400/30 px-2 py-1 text-[9px] text-emerald-700">กำลังทำ</span>}</div><div className="mt-2 text-xs text-slate-500">ทำ {ready}/{qty} · เสิร์ฟ {called}/{qty}</div><div className="mt-3 flex flex-wrap gap-2">{isPrimary&&!x.prepSelected&&<button disabled={busy!==""} onClick={()=>act(o.id,i,"select")} className="rounded-full border border-[#d4af37]/40 px-3 py-2 text-xs text-[#7a5d0b] disabled:opacity-30">เลือกทำก่อน</button>}<button disabled={busy!==""||ready>=qty} onClick={()=>act(o.id,i,"start",ready+1)} className="rounded-full border border-slate-200 px-3 py-2 text-xs disabled:opacity-30">ทำถัดไป</button><button disabled={busy!==""||called>=ready} onClick={()=>act(o.id,i,"finish",called+1)} className="rounded-full bg-[#d4af37] px-3 py-2 text-xs font-bold text-black disabled:opacity-30">เสร็จ/เรียก</button></div></div>})}</div><button disabled={busy!==""||!(o.items||[]).every(x=>(Number(x.calledQty)||0)>=(Number(x.qty)||0))} onClick={()=>ret(o.id)} className="mt-4 w-full rounded-full border border-emerald-400/30 py-3 text-sm font-semibold text-emerald-700 disabled:opacity-25">ส่งมอบคิวนี้</button></div>)}</div></section>}
