"use client";
import {useState} from "react"; import {Download,ShieldCheck,Upload} from "lucide-react"; import AuthGate from "@/components/auth-gate"; import {api,type Session} from "@/lib/api-client";
type Preview={recordCounts:Record<string,number>;dataVersion?:string;schemaVersion:number};
export default function Backup(){return <AuthGate>{s=><View session={s}/>}</AuthGate>}
function View({session}:{session:Session}){const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[backup,setBackup]=useState<any>(null),[revision,setRevision]=useState(0),[replace,setReplace]=useState(false),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);if(session.user.role!=="admin")return <div className="grid h-full place-items-center text-neutral-500">Admin permission required</div>;
async function exportData(){setBusy(true);setMsg("");try{const r=await api<any>("/api/admin/backup/export");const blob=new Blob([JSON.stringify(r,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="field-pos-full-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(url);setMsg("ส่งออก Full Backup สำเร็จ")}finally{setBusy(false)}}
async function inspect(f:File){setFile(f);setPreview(null);setMsg("");try{const candidate=JSON.parse(await f.text());const p=await api<Preview>("/api/admin/backup/preview",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({backup:candidate})});const meta=await api<any>("/api/state/meta");setBackup(candidate);setPreview(p);setRevision(Number(meta.revision)||0)}catch(e:any){setMsg("ไฟล์ไม่ถูกต้อง: "+e.message)}}
async function restore(){if(!backup||!preview||!replace)return;setBusy(true);setMsg("");try{const r=await api<any>("/api/admin/backup/restore",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({backup,expectedRevision:revision,confirm:true})});setMsg("กู้คืน Full Backup สำเร็จ · revision "+r.revision);setPreview(null);setFile(null);setBackup(null);setReplace(false)}catch(e:any){setMsg(e.message==="revision_conflict"?"ข้อมูลบนเซิร์ฟเวอร์เปลี่ยนแล้ว กรุณาตรวจไฟล์ใหม่":e.message)}finally{setBusy(false)}}
return <section className="soft-scroll h-full overflow-auto p-5 md:p-7"><p className="gold m-0 text-[10px] font-bold tracking-[.3em]">DISASTER RECOVERY</p><h1 className="mt-1 text-2xl font-semibold">FULL BACKUP / RESTORE</h1><div className="mt-5 grid max-w-4xl gap-4 lg:grid-cols-2"><div className="glass card p-6"><Download className="gold"/><h2 className="mt-4 text-lg">Export Full Backup</h2><p className="mt-2 text-sm text-neutral-400">รวม State, Stock Ledger, Cost Snapshots, Recipe Versions, Purchase Records และ Cost History ในไฟล์เดียว</p><button disabled={busy} onClick={exportData} className="mt-5 w-full rounded-full bg-[#d4af37] py-3 font-bold text-black disabled:opacity-40">DOWNLOAD FULL BACKUP</button></div><div className="glass card p-6"><Upload className="gold"/><h2 className="mt-4 text-lg">Restore Preview</h2><p className="mt-2 text-sm text-neutral-400">ตรวจ Schema, จำนวนข้อมูล และความสัมพันธ์ก่อนเขียนทุกตารางพร้อมกันใน Transaction เดียว</p><label className="mt-5 block cursor-pointer rounded-[22px] border border-dashed border-white/15 p-5 text-center text-sm text-neutral-400"><input type="file" accept="application/json,.json" className="hidden" onChange={e=>e.target.files?.[0]&&inspect(e.target.files[0])}/>{file?.name||"เลือกไฟล์ Full Backup JSON"}</label>{preview&&<div className="mt-4 rounded-[22px] bg-white/[.03] p-4"><div className="flex items-center gap-2 text-emerald-300"><ShieldCheck size={16}/><b>FULL DR PREVIEW PASSED · Schema {preview.schemaVersion}</b></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-neutral-400">{Object.entries(preview.recordCounts||{}).map(([k,v])=><div key={k} className="flex justify-between"><span>{k}</span><b className="text-white">{v}</b></div>)}</div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>ยืนยันแทน State และ Ledger ปัจจุบัน revision {revision}</label><button disabled={busy||!replace} onClick={restore} className="mt-4 w-full rounded-full border border-red-400/30 py-3 font-bold text-red-200 disabled:opacity-30">RESTORE FULL BACKUP</button></div>}</div></div>{msg&&<div className="mt-4 max-w-4xl rounded-2xl border border-white/10 p-4 text-sm">{msg}</div>}</section>}
