"use client";
import {useState} from "react"; import {Download,ShieldCheck,Upload} from "lucide-react"; import AuthGate from "@/components/auth-gate"; import {api,type Session} from "@/lib/api-client";
type Preview={counts:Record<string,number>;dataVersion?:number};
export default function Backup(){return <AuthGate>{s=><View session={s}/>}</AuthGate>}
function View({session}:{session:Session}){const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[state,setState]=useState<any>(null),[revision,setRevision]=useState(0),[replace,setReplace]=useState(false),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);if(session.user.role!=="admin")return <div className="grid h-full place-items-center text-neutral-500">Admin permission required</div>;
async function exportData(){setBusy(true);setMsg("");try{const r=await api<any>("/api/state");const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),revision:r.revision,state:r.state},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="field-pos-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(url);setMsg("ส่งออกข้อมูลสำเร็จ")}finally{setBusy(false)}}
async function inspect(f:File){setFile(f);setPreview(null);setMsg("");try{const raw=JSON.parse(await f.text()),candidate=raw.state??raw;const p=await api<Preview>("/api/import/preview",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({state:candidate})});const meta=await api<any>("/api/state/meta");setState(candidate);setPreview(p);setRevision(Number(meta.revision)||0)}catch(e:any){setMsg("ไฟล์ไม่ถูกต้อง: "+e.message)}}
async function restore(){if(!state||!preview)return;setBusy(true);setMsg("");try{const r=await api<any>("/api/import/commit",{method:"POST",headers:{"X-CSRF-Token":session.csrf},body:JSON.stringify({state,expectedRevision:revision,replace:revision>0?replace:false})});setMsg("กู้คืนสำเร็จ · revision "+r.revision);setPreview(null);setFile(null)}catch(e:any){setMsg(e.message==="replacement_requires_explicit_choice"?"ต้องยืนยันการแทนข้อมูลปัจจุบัน":e.message==="revision_conflict"?"ข้อมูลบนเซิร์ฟเวอร์เปลี่ยนแล้ว กรุณาตรวจไฟล์ใหม่":e.message)}finally{setBusy(false)}}
return <section className="soft-scroll h-full overflow-auto p-5 md:p-7"><p className="gold m-0 text-[10px] font-bold tracking-[.3em]">DISASTER RECOVERY</p><h1 className="mt-1 text-2xl font-semibold">BACKUP / RESTORE</h1><div className="mt-5 grid max-w-4xl gap-4 lg:grid-cols-2"><div className="glass card p-6"><Download className="gold"/><h2 className="mt-4 text-lg">Export Backup</h2><p className="mt-2 text-sm text-neutral-400">ดาวน์โหลด snapshot ปัจจุบันของเมนู สูตร สต็อก ยอดขาย ค่าใช้จ่าย ลูกค้า และการตั้งค่า เพื่อเก็บไว้นอกระบบ</p><button disabled={busy} onClick={exportData} className="mt-5 w-full rounded-full bg-[#d4af37] py-3 font-bold text-black disabled:opacity-40">DOWNLOAD JSON BACKUP</button></div><div className="glass card p-6"><Upload className="gold"/><h2 className="mt-4 text-lg">Restore Preview</h2><p className="mt-2 text-sm text-neutral-400">ระบบจะตรวจไฟล์และแสดงจำนวนข้อมูลก่อนเขียนจริง การ restore จะเก็บเวอร์ชันเดิมไว้ในประวัติ</p><label className="mt-5 block cursor-pointer rounded-[22px] border border-dashed border-white/15 p-5 text-center text-sm text-neutral-400"><input type="file" accept="application/json,.json" className="hidden" onChange={e=>e.target.files?.[0]&&inspect(e.target.files[0])}/>{file?.name||"เลือกไฟล์ Backup JSON"}</label>{preview&&<div className="mt-4 rounded-[22px] bg-white/[.03] p-4"><div className="flex items-center gap-2 text-emerald-300"><ShieldCheck size={16}/><b>PREVIEW PASSED</b></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-neutral-400">{Object.entries(preview.counts||{}).map(([k,v])=><div key={k} className="flex justify-between"><span>{k}</span><b className="text-white">{v}</b></div>)}</div>{revision>0&&<label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>ยืนยันแทนข้อมูลปัจจุบัน revision {revision}</label>}<button disabled={busy||(revision>0&&!replace)} onClick={restore} className="mt-4 w-full rounded-full border border-red-400/30 py-3 font-bold text-red-200 disabled:opacity-30">RESTORE VERIFIED BACKUP</button></div>}</div></div>{msg&&<div className="mt-4 max-w-4xl rounded-2xl border border-white/10 p-4 text-sm">{msg}</div>}</section>}
